- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present

    - name: Install pymsql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present

    - name: Start maridb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes


    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Adding one user name bob in the database 'accounts'
      community.mysql.mysql_user:
        name: bob
        password: 'admin943'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

