- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create key pair
      ec2_key:
        name: my_keypair
        region: us-east-1
        state: present
      register: keyout

        #- name: print key
        #debug:
        #var: keyout

    - name: save private key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./my_keypair.pem
      when: keyout.changed

    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "my_keypair"
        #vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
        #network_interfaces:
        #- assign_public_ip: true
        image_id: ami-01816d07b1128cd2d
        exact_count: 1
        region: us-east-1
        tags:
            Environment: Testing

