- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create key pair
      ec2_key:
        name: my_keypair
        region: us-east-1
        state: present
      register: keyout

        #- name: print key
        #debug:
        #var: keyout

    - name: save private key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./my_keypair.pem
      when: keyout.changed

